Write unit tests for all b zone api endpoints Part 1
NeaGogu/B-zone pull request #119
Opened 2023-03-28 17:19 UTC by Patricijia

2023-03-28 18:21 UTC, VictorVader submitted a review, later dismissed

2023-03-29 09:35 UTC, NeaGogu requested changes

2023-03-29 09:35 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +		http.Error(w, "uid is not a string", http.StatusInternalServerError)
since we need the user id as an int, why not store it directly as an int in the context. The idea of moving it was to remove all the boilerplate needed when extracting the uid. https://pkg.go.dev/context#WithValue from this looks like the key and value can be any value.

2023-03-29 09:35 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
same here with uid as int

2023-03-29 09:35 UTC, NeaGogu commented on backend/cmd/web/routes.go
> +func JWTRequestChecker(next http.Handler) http.Handler {
comment your functions :)

2023-03-29 09:35 UTC, NeaGogu commented on backend/cmd/web/routes.go
> +		ctx := context.WithValue(r.Context(), ContextUserKey, uid)
add the user id as an int

2023-03-29 09:35 UTC, NeaGogu commented on backend/cmd/web/routes.go
> +		r.Use(JWTRequestChecker)
add this middleware after the one below. First we should check if the token is accepted by bumbal.

2023-03-29 14:09 UTC, Patricijia commented on backend/cmd/web/routes.go
> +func JWTRequestChecker(next http.Handler) http.Handler {
learning from the best how not to ;)

2023-03-29 14:58 UTC, Patricijia commented
@VictorVader @NeaGogu this is important cuz i want to merge it today

2023-03-29 15:00 UTC, NeaGogu commented
This can wait my carbonara can not 🤌🍝

2023-03-29 15:26 UTC, NeaGogu commented on backend/cmd/web/routes.go
> +func JWTRequestChecker(next http.Handler) http.Handler {
why is this still not documented???

2023-03-29 15:28 UTC, NeaGogu approved these changes

2023-03-29 15:33 UTC, VictorVader approved these changes

2023-03-29 15:35 UTC, merged