Dockerized frontend
NeaGogu/B-zone pull request #123
Opened 2023-03-29 14:16 UTC by Patricijia

2023-03-29 15:08 UTC, VictorVader submitted a review, later dismissed

2023-03-30 08:39 UTC, NeaGogu requested changes

2023-03-30 08:39 UTC, NeaGogu commented on frontend/docker-compose.yml
> +        - 3000:30
delete this file

2023-03-30 08:39 UTC, NeaGogu commented on frontend/.dockerignore
> +*/node_modules
move this to project root

2023-03-30 08:43 UTC, Patricijia commented on frontend/docker-compose.yml
> +        - 3000:30
@NeaGogu wait the entire file?

2023-03-30 08:44 UTC, NeaGogu commented on frontend/docker-compose.yml
> +        - 3000:30
do you use it?

2023-03-30 08:44 UTC, NeaGogu commented on frontend/docker-compose.yml
> +        - 3000:30
if no, then yes :laughing:

2023-03-30 08:46 UTC, NeaGogu approved these changes

2023-03-30 08:47 UTC, VictorVader approved these changes

2023-03-30 08:47 UTC, merged