Changed the handlers
NeaGogu/B-zone pull request #129
Opened 2023-03-30 13:19 UTC by VictorVader

So that all the activities from Bumbal are properly collected and filtered

2023-03-30 13:25 UTC, Patricijia commented on backend/cmd/web/routes.go
> -		fmt.Println(userId)
thanks:)

2023-03-30 13:27 UTC, Patricijia submitted a review, later dismissed

2023-03-30 16:22 UTC, NeaGogu submitted a review, later dismissed

2023-03-30 16:22 UTC, NeaGogu commented on backend/internal/bumbal/handler_helpers.go
> +				return nil, err
if the action for both cases is the same then why handle them as 2 separate cases? Just put them under `default`.

2023-03-30 16:22 UTC, NeaGogu commented on backend/internal/bumbal/handler_helpers.go
> +			}
If we need to do many requests (as you mentioned around 20), it would be useful to run each loop in a goroutine but be careful about how you add the response to the array to prevent race conditions

2023-03-30 16:26 UTC, Lucasmeteenc submitted a review, later dismissed
Add descriptions of the parameters, some comments (like line 82) could be expanded to explain more

2023-03-30 17:00 UTC, PhilipWaldman commented on backend/internal/bumbal/handler_helpers.go
> +					return nil, err
Being this far indented makes it hard to understand. 
Since all the error status codes return the same I would recommend something like this:
```
if response.StatusCode != http.StatusOK {
    return nil, http.Error(...)
}
// StatusOK case code here
```

2023-03-30 17:04 UTC, PhilipWaldman commented on backend/internal/bumbal/handler_helpers.go
> +			}
This is indeed a good use case for goroutines. Look into WaitGroups to ensure you have gotten all responses before continueing

2023-03-30 17:32 UTC, NeaGogu commented on backend/internal/bumbal/handler_helpers.go
> +					return nil, err
yep I agree with philip

2023-03-30 18:42 UTC, VictorVader commented on backend/internal/bumbal/handler_helpers.go
> +			}
done

2023-03-30 19:04 UTC, Lucasmeteenc requested changes

2023-03-30 19:04 UTC, Lucasmeteenc commented on backend/internal/bumbal/handler_helpers.go
> +				mutex.Lock()
Why do you lock this? Channels don't need to be locked?

2023-03-30 19:18 UTC, Lucasmeteenc requested changes

2023-03-30 19:18 UTC, Lucasmeteenc commented on backend/internal/bumbal/handler_helpers.go
> +				partResponse, _ := requestBumbalActivity(w, r, reqBody)
Don't ignore error...

2023-03-30 19:24 UTC, VictorVader commented on backend/internal/bumbal/handler_helpers.go
> +				mutex.Lock()
because it's a variable accessed by multiple goroutines

2023-03-30 19:25 UTC, VictorVader commented on backend/internal/bumbal/handler_helpers.go
> +				partResponse, _ := requestBumbalActivity(w, r, reqBody)
Here I am just collecting the responses, I take care of them later in the code anyway

2023-03-31 08:40 UTC, PhilipWaldman submitted a review, later dismissed

2023-03-31 10:35 UTC, PhilipWaldman approved these changes

2023-03-31 17:57 UTC, Lucasmeteenc approved these changes

2023-03-31 17:57 UTC, Lucasmeteenc approved these changes

2023-03-31 18:00 UTC, merged