Docker command for development
NeaGogu/B-zone pull request #139
Opened 2023-04-04 17:22 UTC by Patricijia

docker-compose -f docker-compose-dev.yml up

2023-04-05 09:06 UTC, NeaGogu requested changes

2023-04-05 09:06 UTC, NeaGogu commented on .github/workflows/docker-image.yml
> -    runs-on: ubuntu-latest
no windows

2023-04-05 09:06 UTC, NeaGogu commented on .github/workflows/go.yml
> +    runs-on: windows-latest
no windows

2023-04-05 09:06 UTC, NeaGogu commented on BuildBackendDev.Dockerfile
> +CMD ["./b-zone"]
this makes a very big image because you do everything in one step

2023-04-05 09:06 UTC, NeaGogu commented on BuildFrontendDev.Dockerfile
> +COPY --from=builder /app/build .
you haven't defined any stage called builder

2023-04-05 09:06 UTC, NeaGogu commented on BuildFrontendDev.Dockerfile
> +COPY --from=builder /app/build .
also you cannot use the --from tag unless you define another STEP (check the other Dockerfile for frontend)

2023-04-05 09:06 UTC, NeaGogu commented on BuildFrontendDev.Dockerfile
> +ENV NODE_ENV=development
how is node_env supposed to change behaviour ?

2023-04-05 09:06 UTC, NeaGogu commented on docker-compose-dev.yml
> +      - bzone_network
make a different network so it doesnt conflict  if "prod" and "dev" run at the same time

2023-04-05 09:06 UTC, NeaGogu commented on docker-compose-dev.yml
> +    image: bzone/backend_image:1.0.0
name the image differently if you want to have a different one for "dev'

2023-04-05 09:06 UTC, NeaGogu commented on docker-compose-dev.yml
> +    image: goglete/sep_bzone_frontend:latest
here you are specifying a build directive but you point to an image that's on my docker hub. Change the name of the image

2023-04-17 14:00 UTC, Patricijia commented
@NeaGogu works for me with docker-compose -f docker-compose-dev.yml up -d, good job

2023-04-17 16:01 UTC, PhilipWaldman approved these changes

2023-04-17 19:20 UTC, VictorVader approved these changes

2023-04-18 16:33 UTC, NeaGogu approved these changes

2023-04-18 16:33 UTC, merged