Added b-Zone API Models
NeaGogu/B-zone pull request #60
Opened 2023-03-07 08:47 UTC by Patricijia

2023-03-07 08:51 UTC, Patricijia commented on backend/cmd/web/models/users_model.go
> +type UserDBModel struct {
UsersDBModel* 🥴

2023-03-07 08:56 UTC, Patricijia commented on backend/cmd/web/models/users_model.go
> +	//
And I just realized that we forgot the most important part - how to relate users to their Zones. Either we could store **user ID in the ZonesPlotModel** or the **[]ZonesPlot in the UsersModel**

2023-03-07 15:52 UTC, VictorVader approved these changes

2023-03-07 15:53 UTC, VictorVader submitted a review, later dismissed

2023-03-08 18:07 UTC, NeaGogu requested changes

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +}
What should be the difference between these 2?

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +}
I don't think we would need this kind of getter. Also returning the zero value of the field in case it does not exist might lead to shooting ourselves in the foot. The type of getter below this (the `Get..Ok`) would be more idiomatic and less error-prone, because you explicitly tell the user (with the returned `bool`  value) that something was not ok, and it's up to the user to decide how to handle that. They could even choose to ignore the `bool` completely and that would be the same as the `GetId()` method.

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +	// zones plots per user
Dont store fields with primitive types as pointers. You dont want to return the pointer to those values anyway, cause the user might mutate the field without wanting to when performing operations with that value.

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +	// zones plots per user
Same for all the other Models

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +}
Same for all the other methods

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +func (o *UsersModel) GetIdOk() (*int64, bool) {
you can even name the return values to be more specific for the user. E.g `(id int64, ok bool)`

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/zone_model.go
> +	ZoneDrivingTime *int64 `json:"zone_driving_time,omitempty"`
same issue as above

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/zone_model.go
> +}
same question as above

2023-03-08 18:07 UTC, NeaGogu commented on backend/cmd/web/models/zone_model.go
> +
same comment as above

2023-03-09 08:52 UTC, Patricijia commented on backend/cmd/web/models/users_model.go
> +	// zones plots per user
This is how Bumbal stores stuff in their API. So for all the primitive types e.g. string, int I will delete the pointer, right? But I'll leave "*" for Model types?

2023-03-09 08:53 UTC, Patricijia commented on backend/cmd/web/models/users_model.go
> +}
So I'll delete all the "get" and "set" methods and leave only GetSomethingOk. Right?

2023-03-09 09:41 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +}
The "Set" methods are fine, just the "get" ones

2023-03-09 09:45 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +	// zones plots per user
Yeah that sounds good. 
![image](https://user-images.githubusercontent.com/70640237/223983007-a600fe78-54a4-4be4-a207-ad0c3a6b446e.png)
Do you mean the `$int64` thing? I think that just refers to what type of interger it is, not that it's a pointer.

2023-03-09 09:48 UTC, NeaGogu commented on backend/cmd/web/models/users_model.go
> +	//
I would say store the ZonesPlots ids in the UserModel

2023-03-10 09:29 UTC, NeaGogu submitted a review, later dismissed

2023-03-10 09:30 UTC, NeaGogu commented
@Patricijia resolve the conflicts before merging pls. And @VictorVader review pls

2023-03-10 09:32 UTC, NeaGogu submitted a review, later dismissed

2023-03-10 11:17 UTC, VictorVader submitted a review, later dismissed

2023-03-10 16:25 UTC, Patricijia commented
@NeaGogu pls

2023-03-10 16:36 UTC, NeaGogu commented
Bruh I'm at the gym 😂😂

2023-03-10 20:24 UTC, NeaGogu commented
![image](https://user-images.githubusercontent.com/70640237/224421471-adeecf06-1ac8-479e-891f-5337d97dfada.png)
Didn't we decide we're gonna change them to Plot, Zone and ZoneRange? :laughing:

2023-03-10 20:25 UTC, NeaGogu submitted a review, later dismissed

2023-03-11 11:06 UTC, VictorVader approved these changes

2023-03-11 14:01 UTC, NeaGogu approved these changes

2023-03-11 14:14 UTC, merged