Added and API endpoint which, upon request, extracts the user id from…
NeaGogu/B-zone pull request #84
Opened 2023-03-14 12:45 UTC by VictorVader

… the token, queries the database, and returns the plot IDs and names related to the specified user.

2023-03-14 20:05 UTC, Patricijia submitted a review, later dismissed

2023-03-14 20:05 UTC, Patricijia commented on backend/cmd/web/plotids_handler.go
> +			reqPlotIDs, err := app.bzoneDbModel.GetPlotIDs(userId)
I wonder what kind og user id they will send. Cuz in Bumbal unique user id is uuid but we'll have another user_id for B-Zone. I think they would send us Bumbal user id which is `uuid`

2023-03-14 20:05 UTC, Patricijia commented on backend/cmd/web/plotids_handler.go
> +		if key == "user_id" {
lgtm but just for my understanding, do you get the user_id from the token?

2023-03-15 08:49 UTC, NeaGogu requested changes

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +	jwToken := r.Header.Get("Authorization") // -> "Bearer <TOKEN>"
I know we already have the jwt checker in place but **it's good practice to check if this header actually exists** when you ask for it. In the future we might just extract what we need from the JWT and pass it in the request Context to make stuff easier to test

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +	jwToken = jwToken[len("Bearer "):]       // remove "Bearer "
same here, check if Bearer exists in the string first (it might be a "Basic" auth and not a Bearer). You can use this method https://pkg.go.dev/strings#Contains

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +	jwToken = jwToken[len("Bearer "):]       // remove "Bearer "
also this is a good example that not checking if `jwToken` is en empty string, attempting to take a slice from it might throw an IndexOutOfBounds error and crash the whole request.

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +		fmt.Println(err.Error())
dont use fmt.Println. If you really need, use `app.erroLog.Println`

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +		if key == "user_id" {
yeah it's the uid from the token

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +			reqPlotIDs, err := app.bzoneDbModel.GetPlotIDs(userId)
from what I noticed, `uuid` always changes in their token. `user_id` and `user_uuid` are consistent with different tokens but idk why they have two

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/plotids_handler.go
> +			json.NewEncoder(w).Encode(reqPlotIDs)
check the error

2023-03-15 08:49 UTC, NeaGogu commented on backend/cmd/web/routes.go
> +		})
move this route in the group above. The group above is meant for all routes that require authorization

2023-03-15 08:49 UTC, NeaGogu commented on backend/internal/models/plotids.go
> +//}
remove commented code

2023-03-15 11:05 UTC, NeaGogu approved these changes

2023-03-15 11:06 UTC, merged