Updated the Get saved zones endpoint
NeaGogu/B-zone pull request #85
Opened 2023-03-14 12:56 UTC by Patricijia

2023-03-14 13:54 UTC, VictorVader submitted a review, later dismissed

2023-03-15 08:53 UTC, NeaGogu requested changes

2023-03-15 08:53 UTC, NeaGogu commented on backend/cmd/web/bzone_plot_handler.go
> +	}
move database stuff to /intern/models in a separate function (look how I did it for zipcodes). That way the functionality can be tested individually.

2023-03-15 12:29 UTC, Patricijia commented on backend/cmd/web/bzone_plot_handler.go
> +	}
@NeaGogu the entire GetBZonePlot?

2023-03-15 12:38 UTC, Patricijia commented on backend/cmd/web/bzone_plot_handler.go
> +	}
Because I dont have subqueries

2023-03-15 12:58 UTC, Patricijia commented on backend/cmd/web/bzone_plot_handler.go
> +	}
yea i think i understood

2023-03-15 14:35 UTC, NeaGogu commented on backend/cmd/web/bzone_plot_handler.go
> +	}
just the selected code (lines 20 - 31)

2023-03-15 14:35 UTC, NeaGogu commented
and fix the conflicts pls

2023-03-17 11:49 UTC, VictorVader submitted a review, later dismissed
Watch out for the conflicts!

2023-03-17 14:36 UTC, VictorVader approved these changes

2023-03-17 14:52 UTC, NeaGogu approved these changes

2023-03-17 14:52 UTC, merged